# Initialize Homebrew if it exists
if [[ -f "/opt/homebrew/bin/brew" ]]; then
    eval "$(/opt/homebrew/bin/brew shellenv)"
elif [[ -f "/usr/local/bin/brew" ]]; then
    eval "$(/usr/local/bin/brew shellenv)"
fi

# Machine-specific overrides (gitignored, generated by setup.sh)
[[ -f ~/.zshrc.local ]] && source ~/.zshrc.local

# Set the directory where to store zinit and plugins
ZINIT_HOME="${XDG_DATA_HOME:-${HOME}/.local/share}/zinit/zinit.git"

# Download Zinit, if it doesn’t exist
if [ ! -d "$ZINIT_HOME" ]; then
	mkdir -p "$(dirname $ZINIT_HOME)"
	git clone https://github.com/zdharma-continuum/zinit.git "$ZINIT_HOME"
fi

# Source/Load zinit
source "${ZINIT_HOME}/zinit.zsh"

# Plugins go here:

# ZSH Completion
zinit light zsh-users/zsh-completions
# Load Completions
autoload -U compinit && compinit -C
zinit cdreplay -q

# ZSH Autosuggestions
zinit light zsh-users/zsh-autosuggestions

# FZF Tab
zinit light Aloxaf/fzf-tab

# EZA replacement for ls (only when eza is installed — else it errors every startup)
command -v eza >/dev/null && zinit light z-shell/zsh-eza

# Syntax Highlighting (must be last)
zinit light zsh-users/zsh-syntax-highlighting

# Add in snippets
zinit snippet OMZP::git
zinit snippet OMZP::sudo
zinit snippet OMZP::command-not-found


# Keybindings
bindkey '^y' autosuggest-accept


# History
HISTSIZE=50000
HISTFILE=~/.zsh_history
SAVEHIST=$HISTSIZE
HISTDUP=erase
setopt appendhistory
setopt sharehistory
setopt hist_ignore_space
setopt hist_ignore_all_dups
setopt hist_save_no_dups
setopt hist_ignore_dups
setopt hist_find_no_dups

# Completion styling
zstyle ':completion:*' matcher-list 'm:{a-z}={A-Za-z}'
zstyle ':completion:*' list-colors "${(s.:.)LS_COLORS}"
zstyle ':completion:*' menu no
zstyle ':fzf-tab:complete:cd:*' fzf-preview 'eza -la --icons --git --color=always --group-directories-first $realpath 2>/dev/null || ls -la --color $realpath'
zstyle ':fzf-tab:complete:__zoxide_z:*' fzf-preview 'eza -la --icons --git --color=always --group-directories-first $realpath 2>/dev/null || ls -la --color $realpath'
zstyle ':fzf-tab:complete:__zoxide_zi:*' fzf-preview 'eza -la --icons --git --color=always --group-directories-first $realpath 2>/dev/null || ls -la --color $realpath'

# Aliases
alias ff='ls | fzf'
command -v bat >/dev/null && alias cat='bat'
# eza-based ls family; falls back to plain `ls -G` when eza isn't installed
# (e.g. a headless server profile) so `ls` never breaks.
if command -v eza >/dev/null; then
  alias ls='eza --group-directories-first --icons'
  alias l='eza --git-ignore --group-directories-first --icons'
  alias ll='eza --all --header --long --group-directories-first --icons'
  alias llm='eza --all --header --long --sort=modified --group-directories-first --icons'
  alias la='eza -lbhHigUmuSa'
  alias lx='eza -lbhHigUmuSa@'
  alias lt='eza --tree --group-directories-first --icons'
  alias tree='eza --tree --group-directories-first --icons'
else
  alias ls='ls -G'
  alias l='ls -G'
  alias ll='ls -lhG'
  alias la='ls -lhAG'
fi
alias oo='cd ${OSTRICH_VAULT:-$HOME/Documents/ObsidianSyncedVaults/SecondBrain}/'
alias bup='brew update && brew upgrade && exec zsh'
function ops() {
  local vault="${OSTRICH_VAULT:-$HOME/Documents/ObsidianSyncedVaults/SecondBrain}"
  if [ -n "$TMUX" ]; then
    sesh connect LCARS
  elif tmux has-session -t LCARS 2>/dev/null; then
    tmux attach -t LCARS
  else
    tmux new-session -d -s LCARS -c "$vault" \
      && ~/dotfiles/tmux/scripts/lcars.sh \
      && tmux attach -t LCARS
  fi
}
command -v nvim >/dev/null && alias nfz='nvim $(fzf -m --preview="bat --color=always {}")'

# yazi wrapper function
if command -v yazi >/dev/null; then
    function yy() {
	local tmp="$(mktemp -t "yazi-cwd.XXXXXX")"
	yazi "$@" --cwd-file="$tmp"
	if cwd="$(cat -- "$tmp")" && [ -n "$cwd" ] && [ "$cwd" != "$PWD" ]; then
		builtin cd -- "$cwd"
	fi
	rm -f -- "$tmp"
    }
fi

# Local binaries on PATH — must precede the fzf/zoxide init below so user-level
# installs in ~/.local/bin (e.g. on a server) are found and initialized.
export PATH="$HOME/.local/bin:$PATH"

# Initialize fzf
command -v fzf >/dev/null && eval "$(fzf --zsh)"

# Initialize zoxide with cd override
command -v zoxide >/dev/null && eval "$(zoxide init --cmd cd zsh)"

# Zoxide aliases
alias z="cd"    # Short alias for zoxide-powered cd
alias zi="cdi"  # Short alias for interactive directory selection
alias zs="zoxide query -s"  # Show zoxide statistics

# Zoxide environment variables
export _ZO_MAXAGE=10000      # Keep more entries in the database
export _ZO_RESOLVE_SYMLINKS=1 # Resolve symlinks before adding to database

# Set default editor
if command -v nvim >/dev/null; then
    export EDITOR=nvim
else
    export EDITOR=vim
fi

# Initialize thefuck
command -v thefuck >/dev/null && eval "$(thefuck --alias)"



# =====================================================================
# Terminal Workstation foundation (Plan 1)
# =====================================================================

# --- Dotfiles profile marker ---
export DOTFILES_PROFILE="$(cat "$HOME/.dotfiles-profile" 2>/dev/null || echo personal)"

# --- zj: Zellij cold-start / attach-or-create ---
zj() {
    zellij attach main 2>/dev/null || zellij -n main -s main
}

# --- Auto-exec into Zellij on interactive Ghostty launch ---
# Guards: only inside interactive shell, not already inside Zellij,
#         only in Ghostty, only if zellij installed (capability-gated for work Mac).
#         ZELLIJ_SKIP=1 opts out for debugging.
# Note: checks ZELLIJ_SESSION_NAME (not ZELLIJ) because Zellij leaks ZELLIJ
#       into the macOS launchd env, which GUI apps like Ghostty inherit.
if [[ -z "${ZELLIJ_SESSION_NAME:-}" && -z "${ZELLIJ_SKIP:-}" && "${TERM_PROGRAM:-}" == "ghostty" && -o interactive ]]; then
    if command -v zellij >/dev/null 2>&1; then
        unset ZELLIJ
        zellij attach main 2>/dev/null || zellij -n main -s main
    fi
fi

# =====================================================================

# >>> conda initialize >>>
# !! Contents within this block are managed by 'conda init' !!
__conda_setup="$('/Users/raviyadav/anaconda3/bin/conda' 'shell.zsh' 'hook' 2> /dev/null)"
if [ $? -eq 0 ]; then
    eval "$__conda_setup"
else
    if [ -f "/Users/raviyadav/anaconda3/etc/profile.d/conda.sh" ]; then
        . "/Users/raviyadav/anaconda3/etc/profile.d/conda.sh"
    else
        export PATH="/Users/raviyadav/anaconda3/bin:$PATH"
    fi
fi
unset __conda_setup
# <<< conda initialize <<<



# Added by Antigravity CLI installer
export PATH="/Users/raviyadav/.local/bin:$PATH"
